import os
import numpy as np
import shutil
import copy
import SimpleITK as sitk
from tkinter import messagebox, Tk
from slicer_project_generator.scripts.utils import json_reader, json_save
import re
from data_postprocessing.controller_analysis import load_mask, load_labels_mask_sitk
from data_postprocessing.mask_analysis import extract_boundary_curve_world
from data_postprocessing.vtk_analysis import CenterlineExtractor

# from pyarrow import output_stream

template_point = {
    "id": "",
    "label": "",
    "description": "",
    "associatedNodeID": "",
    "position": [],
    "orientation": [-1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0],
    "selected": True,
    "locked": True,
    "visibility": True,
    "positionStatus": "defined"
}

TEMPLATE_MAP = {
    "BasalRing.json":      ("BR - closed",     "BasalRing"),
    "CuspInsertion_L.json": ("LCI",            "CuspInsertion_L"),
    "CuspInsertion_N.json": ("NCI",            "CuspInsertion_N"),
    "CuspInsertion_R.json": ("RCI",            "CuspInsertion_R"),
    "GeometricHeight_L.json": ("LGH",          "GeometricHeight_L"),
    "GeometricHeight_N.json": ("NGH",          "GeometricHeight_N"),
    "GeometricHeight_R.json": ("RGH",          "GeometricHeight_R"),
    "Sinus_LN.json":        ("LNS - closed",   "Sinus_LN"),
    "Sinus_RL.json":        ("RLS - closed",   "Sinus_RL"),
    "Sinus_RN.json":        ("RNS - closed",   "Sinus_RN"),
    "GeometricHeight_L_pred.json": ("LGH_p",          "GeometricHeight_L_pred"),
    "GeometricHeight_N_pred.json": ("NGH_p",          "GeometricHeight_N_pred"),
    "GeometricHeight_R_pred.json": ("RGH_p",          "GeometricHeight_R_pred"),
    "BasalRing_pred.json":         ("BR_p",           "BasalRing_pred"),
    "CuspInsertion_L_pred.json":   ("LCI_p",          "CuspInsertion_L_pred"),
    "CuspInsertion_N_pred.json":   ("NCI_p",          "CuspInsertion_N_pred"),
    "CuspInsertion_R_pred.json":   ("RCI_p",          "CuspInsertion_R_pred"),
}

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def fill_template(case_data, template, key, label_prefix, assoc_node="vtkMRMLScalarVolumeNode1"):
    points_list = []
    for n, point in enumerate(case_data[key], start=1):
        temp_point = copy.deepcopy(template_point)
        temp_point["id"] = str(n)
        temp_point["label"] = f"{label_prefix}_{n}"
        temp_point["associatedNodeID"] = assoc_node
        temp_point["position"] = point.tolist() if isinstance(point, np.ndarray) else point
        points_list.append(temp_point)
    template["markups"][0]["controlPoints"] = points_list
    template["markups"][0]["lastUsedControlPointNumber"] = len(points_list)
    return template

def ref_points(case_data, template):
    allowed_keys = ["R", "L", "N", "RLC", "RNC", "LNC"]
    points_list = []
    n = 1
    for key, point in case_data.items():
        if not key in allowed_keys:
            continue
        temp_point = copy.deepcopy(template_point)
        temp_point["id"] = str(n)
        temp_point["label"] = key
        temp_point["position"] = point[0]
        points_list.append(temp_point)
        n += 1
    template["markups"][0]["controlPoints"] = points_list
    template["markups"][0]["lastUsedControlPointNumber"] = len(points_list)
    return template


def convert_nii_to_nrrd(input_path, output_path, check=True, is_mask=False, segmentation=False):
    image = sitk.ReadImage(input_path)

    if is_mask:
        image = sitk.Cast(image, sitk.sitkUInt8)

    if segmentation:
        image.SetMetaData("Segment0_Color", "0.8 0.8 0.39")
        image.SetMetaData("Segment0_ColorAutoGenerated", "1")
        # image.SetMetaData("Segment0_Extent", "0 471 0 471 0 353")
        image.SetMetaData("Segment0_ID", "Segment_1")
        image.SetMetaData("Segment0_LabelValue", "1")
        image.SetMetaData("Segment0_Layer", "0")
        image.SetMetaData("Segment0_Name", "SegMesh")
        image.SetMetaData("Segment0_NameAutoGenerated", "1")
        image.SetMetaData("Segmentation_ContainedRepresentationNames", "Binary labelmap|Closed surface|")
        image.SetMetaData("Segmentation_MasterRepresentation", "Binary labelmap")
        image.SetMetaData("Segmentation_ReferenceImageExtentOffset", "0 0 0")

    sitk.WriteImage(image, output_path, useCompression=True)

    attention = ""
    if check:
        # Read back the saved NRRD
        converted = sitk.ReadImage(output_path)

        # Checking for property matches
        checks = {
            "Size": image.GetSize() == converted.GetSize(),
            "Spacing": all(abs(a - b) < 1e-6 for a, b in zip(image.GetSpacing(), converted.GetSpacing())),
            "Origin": all(abs(a - b) < 1e-6 for a, b in zip(image.GetOrigin(), converted.GetOrigin())),
            "Direction": all(abs(a - b) < 1e-6 for a, b in zip(image.GetDirection(), converted.GetDirection())),
        }

        for key, result in checks.items():
            if not result:
                attention = "ATTENTION: there are discrepancies between NIfTI and NRRD!"
                break
    return attention

def mrml_generator(file_path, nii_img_path, output_file_path):
    with open(file_path, "r") as f:
        content = f.read()

    # читаем данные из nii
    image = sitk.ReadImage(nii_img_path)
    origin = image.GetOrigin()
    spacing = image.GetSpacing()
    direction = image.GetDirection()

    new_origin = f'{origin[0]} {origin[1]} {origin[2]}'
    new_spacing = f'{spacing[0]} {spacing[1]} {spacing[2]}'
    new_dir = (f'{direction[0]} {direction[1]} {direction[2]} {direction[3]} {direction[4]}'
               f' {direction[5]} {direction[6]} {direction[7]} {direction[8]}')

    # ищем Volume по id
    pattern = r'(<Volume[^>]*id="vtkMRMLScalarVolumeNode1"[^>]*>)'
    match = re.search(pattern, content)
    if match:
        volume_tag = match.group(1)
        # заменяем spacing и origin
        volume_tag_new = re.sub(r'spacing="[^"]+"', f'spacing="{new_spacing}"', volume_tag)
        volume_tag_new = re.sub(r'origin="[^"]+"', f'origin="{new_origin}"', volume_tag_new)
        volume_tag_new = re.sub(r'ijkToRASDirections="[^"]+"', f'ijkToRASDirections="{new_dir}"',
                                volume_tag_new)
        content = content.replace(volume_tag, volume_tag_new)

    # сохраняем изменения обратно
    with open(output_file_path, "w") as f:
        f.writelines(content)


class ProjectGenerator:
    def __init__(self, case_name, output_folder, original_img_folder, original_aorta_mask_folder, case_data,
                 gh_lines_pred_mask_file=None,
                 ci_lines_pred_mask_file=None,
                 br_2d_pred_mask_file=None,
                 base_path="cases"):
        self.case_name = case_name
        self.output_folder = output_folder
        self.original_img_folder = original_img_folder
        self.original_aorta_mask_folder = original_aorta_mask_folder
        self.case_data = case_data
        self.templates_folder = os.path.join(BASE_DIR, "templates")
        self.attentions = []
        self.gh_lines_pred_mask_file = gh_lines_pred_mask_file
        self.ci_lines_pred_mask_file = ci_lines_pred_mask_file
        self.br_2d_pred_mask_file = br_2d_pred_mask_file
        self.gh_pred_data = None

    def _curve_pred_data_generate(self, mask_file, keys, n_samples=20, spline_smoothing=0.1):
        if not mask_file or not os.path.exists(mask_file):
            return {}
        result = {}
        masks_pred, levels_pred = load_mask(mask_file, False)
        vtk_curve_extractor = CenterlineExtractor(spline_smoothing=spline_smoothing)
        for label in range(1, levels_pred + 1):
            if label not in keys:
                continue
            mask_pred = (masks_pred == label).astype(np.uint8)
            mask_sitk = load_labels_mask_sitk(mask_file, label)
            segments = vtk_curve_extractor.run(mask_pred, mask_sitk)
            if segments.GetNumberOfPoints() == 0:
                continue
            pts = np.array([segments.GetPoints().GetPoint(i)
                            for i in range(segments.GetNumberOfPoints())])
            if len(pts) < 2:
                continue
            t = np.concatenate([[0], np.cumsum(np.linalg.norm(np.diff(pts, axis=0), axis=1))])
            t /= t[-1]
            t_new = np.linspace(0, 1, n_samples)
            result[keys[label]] = np.column_stack([np.interp(t_new, t, pts[:, i]) for i in range(3)])
        return result

    def _br_pred_data_generate(self, n_samples=20):
        if not self.br_2d_pred_mask_file or not os.path.exists(self.br_2d_pred_mask_file):
            return {}
        mask_sitk = sitk.ReadImage(self.br_2d_pred_mask_file)
        mask_array = sitk.GetArrayFromImage(mask_sitk)
        boundary_points = extract_boundary_curve_world(mask_array, mask_sitk)
        if len(boundary_points) < 4:
            return {}
        # Remove duplicate endpoint if find_contours closed the contour
        if np.allclose(boundary_points[0], boundary_points[-1], atol=1e-3):
            boundary_points = boundary_points[:-1]
        # endpoint=False: equal spacing without repeating start point at closure
        indices = np.round(np.linspace(0, len(boundary_points), n_samples, endpoint=False)).astype(int)
        return {'BR_p': boundary_points[indices]}

    def check_and_prepare_folder(self, case_folder_path):
        """Проверяет наличие папки и при необходимости очищает её."""
        root = Tk()
        root.withdraw()

        if os.path.exists(case_folder_path):
            answer = messagebox.askyesno(
                "Folder already exists",
                f"The folder '{case_folder_path}' already exists.\n"
                f"Do you want to overwrite it with new files?"
            )
            if not answer:
                messagebox.showinfo("Canceled", "Project generation canceled.")
                root.destroy()
                return False

            shutil.rmtree(case_folder_path)

        os.makedirs(case_folder_path, exist_ok=True)
        root.destroy()
        return True

    def copy_templates(self, case_folder_path):
        """Копирует все файлы из папки templates в папку проекта."""
        attention = convert_nii_to_nrrd(
            os.path.join(self.original_img_folder, self.case_name + ".nii.gz"),
            os.path.join(case_folder_path, "CT_img.nrrd")
        )
        if attention:
            self.attentions.append(f"CT_img.nrrd: {attention}")
        attention = convert_nii_to_nrrd(
            os.path.join(self.original_aorta_mask_folder, self.case_name + ".nii.gz"),
            os.path.join(case_folder_path, "SegMask.seg.nrrd"), is_mask=True, segmentation=True
        )
        if attention:
            self.attentions.append(f"SegMask.seg.nrrd: {attention}")

        for filename in os.listdir(self.templates_folder):
            if filename.endswith(".mrml"):
                if bool(self.gh_pred_data) == ("_pred" in filename[:-5]):
                    mrml_generator(os.path.join(self.templates_folder, filename),
                                   os.path.join(self.original_img_folder, self.case_name + ".nii.gz"),
                                   os.path.join(case_folder_path, filename))
                continue
            elif filename.endswith(".json"):
                template = json_reader(os.path.join(self.templates_folder, filename))
                if filename in TEMPLATE_MAP:
                    key, label_prefix = TEMPLATE_MAP[filename]
                    if key in self.case_data:
                        new_json = fill_template(self.case_data, template, key, label_prefix)
                    elif key in self.gh_pred_data:
                        new_json = fill_template(self.gh_pred_data, template, key, label_prefix)
                    else:
                        continue
                elif filename == 'RefPoints.json':
                    new_json = ref_points(self.case_data, template)
                else:
                    continue
                json_save(new_json, os.path.join(case_folder_path, filename))

    def generate(self):
        self.gh_pred_data = self._curve_pred_data_generate(
            self.gh_lines_pred_mask_file,
            {1: 'RGH_p', 2: 'LGH_p', 3: 'NGH_p'},
            n_samples=10, spline_smoothing=1.0
        )
        self.gh_pred_data.update(self._curve_pred_data_generate(
            self.ci_lines_pred_mask_file, {1: 'RCI_p', 2: 'LCI_p', 3: 'NCI_p'}))
        self.gh_pred_data.update(self._br_pred_data_generate())

        case_folder_path = os.path.join(self.output_folder, self.case_name)

        if not self.check_and_prepare_folder(case_folder_path):
            return None

        self.copy_templates(case_folder_path)

        # сообщение пользователю
        root = Tk()
        root.withdraw()
        msg = f"Project for case '{self.case_name}' created in:\n{case_folder_path}"
        if self.attentions:
            msg += "\n\n" + "\n".join(self.attentions)

        messagebox.showinfo("Success", msg)
        root.destroy()

        return case_folder_path